# Generated by Django 5.1.1 on 2024-10-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
